# yaml-language-server: $schema=../schema/profile.schema.yml
minecraft:
  title: Default Preset
  name: default 
  version: "1.19.2"
  assets: assets
  java: Java17
  mods:
    Quilted Fabric API (QFAPI) / Quilt Standard Libraries (QSL):
      file: mods/quilted-fabric-api.jar:mods/quilted-fabric-api.jar
      description: The standard libraries of the Quilt ecosystem. Essential for your modding experience on Quilt!
      optional: false
      visible: true
  skipCheck:
    - config
  forceCheck:
    - mods
    - libraries
  arguments:
    jvm: 
      - rules:
          - action: enable
            conditions:
              os: darwin
        value: -XstartOnFirstThread
      - rules:
          - action: enable
            conditions:
              os: win32
        value: -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
      - rules:
          - action: enable
            conditions:
              arch: x86
        value: -Xss1M
      - rules:
          - action: enable
            conditions:
              version: ^(Windows 10)
        value:
          - -Dos.name=Windows 10
          - -Dos.version=10.0
      - -XX:+UnlockExperimentalVMOptions
      - -XX:+UseG1GC
      - -XX:G1NewSizePercent=20
      - -XX:G1ReservePercent=20
      - -XX:MaxGCPauseMillis=50
      - -XX:G1HeapRegionSize=32M
      - -XX:+UseJVMCICompiler
      - -Dfile.encoding=UTF-8
  classpath:
    - libraries
    - minecraft.jar
  mainclass: net.minecraft.client.main.Main